{{- if .Values.persistence.app.enabled }}
{{- if not .Values.persistence.app.existingClaim }}
{{- if not .Values.persistence.app.storageClassName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.appPersistenceName" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.app.accessMode }}
  capacity:
    storage: {{ .Values.persistence.app.size }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.app.reclaimPolicy }}
  storageClassName: ""
  nfs:
    server: {{ .Values.persistence.app.nfs.server }}
    path: {{ .Values.persistence.app.nfs.path }}
{{- end }}
{{- end }}
{{- end }}
