{{- if .Values.persistence.app.enabled }}
{{- if not .Values.persistence.app.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.appPersistenceName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.app.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.app.size }}
{{- if .Values.persistence.app.storageClassName }}
  storageClassName: {{ .Values.persistence.app.storageClassName }}
{{- else }}
  storageClassName: ""
  volumeName: {{ include "app.appPersistenceName" . }}
{{- end }}
{{- end }}
{{- end }}
